/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eg.edu.alexu.csd.datastructure.mailServer.cs02_cs32_cs48;

import eg.edu.alexu.csd.datastructure.mailServer.IFolder;
import eg.edu.alexu.csd.datastructure.mailServer.IMail;
import eg.edu.alexu.csd.datastructure.linkedList.cs32_cs02.Single;
import java.awt.Color;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.Time;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.json.simple.parser.ParseException;

/**
 *
 * @author Geek
 */
public class sent extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    String user=" ";
    MailServer mails=new MailServer();
    IMail mail=new IMail();
public Single messages=new Single();
public Single read=new Single();
int index=0;
int multiprevious=0;
int max;
int min;
    public sent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        me1 = new javax.swing.JPanel();
        metext1 = new javax.swing.JLabel();
        me2 = new javax.swing.JPanel();
        metext2 = new javax.swing.JLabel();
        me6 = new javax.swing.JPanel();
        metext6 = new javax.swing.JLabel();
        me3 = new javax.swing.JPanel();
        metext3 = new javax.swing.JLabel();
        me4 = new javax.swing.JPanel();
        metext4 = new javax.swing.JLabel();
        me5 = new javax.swing.JPanel();
        metext5 = new javax.swing.JLabel();
        me7 = new javax.swing.JPanel();
        metext7 = new javax.swing.JLabel();
        me8 = new javax.swing.JPanel();
        metext8 = new javax.swing.JLabel();
        me10 = new javax.swing.JPanel();
        metext10 = new javax.swing.JLabel();
        me9 = new javax.swing.JPanel();
        metext9 = new javax.swing.JLabel();
        next = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        previous = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        img4 = new javax.swing.JLabel();
        img5 = new javax.swing.JLabel();
        img6 = new javax.swing.JLabel();
        img8 = new javax.swing.JLabel();
        img9 = new javax.swing.JLabel();
        img10 = new javax.swing.JLabel();
        img11 = new javax.swing.JLabel();
        refresh = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        previous1 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        error = new javax.swing.JLabel();
        confirmerror = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        me1.setBackground(new java.awt.Color(255, 255, 255));
        me1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        metext1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        metext1.setForeground(new java.awt.Color(102, 102, 102));
        metext1.setText("j");
        metext1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                metext1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout me1Layout = new javax.swing.GroupLayout(me1);
        me1.setLayout(me1Layout);
        me1Layout.setHorizontalGroup(
            me1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(me1Layout.createSequentialGroup()
                .addComponent(metext1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 190, Short.MAX_VALUE))
        );
        me1Layout.setVerticalGroup(
            me1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, me1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(metext1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        me2.setBackground(new java.awt.Color(255, 255, 255));
        me2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        metext2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        metext2.setForeground(new java.awt.Color(102, 102, 102));
        metext2.setText(" ");
        metext2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                metext2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout me2Layout = new javax.swing.GroupLayout(me2);
        me2.setLayout(me2Layout);
        me2Layout.setHorizontalGroup(
            me2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(me2Layout.createSequentialGroup()
                .addComponent(metext2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        me2Layout.setVerticalGroup(
            me2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(me2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(metext2)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        me6.setBackground(new java.awt.Color(255, 255, 255));
        me6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        metext6.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        metext6.setForeground(new java.awt.Color(102, 102, 102));
        metext6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                metext6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout me6Layout = new javax.swing.GroupLayout(me6);
        me6.setLayout(me6Layout);
        me6Layout.setHorizontalGroup(
            me6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(me6Layout.createSequentialGroup()
                .addComponent(metext6, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        me6Layout.setVerticalGroup(
            me6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(me6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(metext6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        me3.setBackground(new java.awt.Color(255, 255, 255));
        me3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        metext3.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        metext3.setForeground(new java.awt.Color(102, 102, 102));
        metext3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                metext3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout me3Layout = new javax.swing.GroupLayout(me3);
        me3.setLayout(me3Layout);
        me3Layout.setHorizontalGroup(
            me3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(me3Layout.createSequentialGroup()
                .addComponent(metext3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        me3Layout.setVerticalGroup(
            me3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, me3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(metext3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        me4.setBackground(new java.awt.Color(255, 255, 255));
        me4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        metext4.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        metext4.setForeground(new java.awt.Color(102, 102, 102));
        metext4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                metext4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout me4Layout = new javax.swing.GroupLayout(me4);
        me4.setLayout(me4Layout);
        me4Layout.setHorizontalGroup(
            me4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(me4Layout.createSequentialGroup()
                .addComponent(metext4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        me4Layout.setVerticalGroup(
            me4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, me4Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(metext4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        me5.setBackground(new java.awt.Color(255, 255, 255));
        me5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        metext5.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        metext5.setForeground(new java.awt.Color(102, 102, 102));
        metext5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                metext5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout me5Layout = new javax.swing.GroupLayout(me5);
        me5.setLayout(me5Layout);
        me5Layout.setHorizontalGroup(
            me5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(me5Layout.createSequentialGroup()
                .addComponent(metext5, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        me5Layout.setVerticalGroup(
            me5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(me5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(metext5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        me7.setBackground(new java.awt.Color(255, 255, 255));
        me7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        metext7.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        metext7.setForeground(new java.awt.Color(102, 102, 102));
        metext7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                metext7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout me7Layout = new javax.swing.GroupLayout(me7);
        me7.setLayout(me7Layout);
        me7Layout.setHorizontalGroup(
            me7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(me7Layout.createSequentialGroup()
                .addComponent(metext7, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        me7Layout.setVerticalGroup(
            me7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(me7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(metext7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        me8.setBackground(new java.awt.Color(255, 255, 255));
        me8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        metext8.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        metext8.setForeground(new java.awt.Color(102, 102, 102));
        metext8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                metext8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout me8Layout = new javax.swing.GroupLayout(me8);
        me8.setLayout(me8Layout);
        me8Layout.setHorizontalGroup(
            me8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(me8Layout.createSequentialGroup()
                .addComponent(metext8, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        me8Layout.setVerticalGroup(
            me8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(me8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(metext8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        me10.setBackground(new java.awt.Color(255, 255, 255));
        me10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        metext10.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        metext10.setForeground(new java.awt.Color(102, 102, 102));
        metext10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                metext10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout me10Layout = new javax.swing.GroupLayout(me10);
        me10.setLayout(me10Layout);
        me10Layout.setHorizontalGroup(
            me10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(me10Layout.createSequentialGroup()
                .addComponent(metext10, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        me10Layout.setVerticalGroup(
            me10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, me10Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(metext10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        me9.setBackground(new java.awt.Color(255, 255, 255));
        me9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        metext9.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        metext9.setForeground(new java.awt.Color(102, 102, 102));
        metext9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                metext9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout me9Layout = new javax.swing.GroupLayout(me9);
        me9.setLayout(me9Layout);
        me9Layout.setHorizontalGroup(
            me9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(me9Layout.createSequentialGroup()
                .addComponent(metext9, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        me9Layout.setVerticalGroup(
            me9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(me9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(metext9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        next.setBackground(new java.awt.Color(0, 153, 255));

        jLabel21.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Next");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel21MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel21MouseExited(evt);
            }
        });

        javax.swing.GroupLayout nextLayout = new javax.swing.GroupLayout(next);
        next.setLayout(nextLayout);
        nextLayout.setHorizontalGroup(
            nextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nextLayout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addContainerGap())
        );
        nextLayout.setVerticalGroup(
            nextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        previous.setBackground(new java.awt.Color(0, 153, 255));
        previous.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                previousMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                previousMouseExited(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Previous");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel22MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel22MouseExited(evt);
            }
        });

        javax.swing.GroupLayout previousLayout = new javax.swing.GroupLayout(previous);
        previous.setLayout(previousLayout);
        previousLayout.setHorizontalGroup(
            previousLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, previousLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        previousLayout.setVerticalGroup(
            previousLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        img1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Geek\\Documents\\NetBeansProjects\\data-structure\\src\\blue-mail-open-icon~1.png")); // NOI18N

        img8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Geek\\Documents\\NetBeansProjects\\data-structure\\src\\email-icoon~1.png")); // NOI18N

        refresh.setBackground(new java.awt.Color(0, 153, 255));
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshMouseClicked(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Refresh");
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel24MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel24MouseExited(evt);
            }
        });

        javax.swing.GroupLayout refreshLayout = new javax.swing.GroupLayout(refresh);
        refresh.setLayout(refreshLayout);
        refreshLayout.setHorizontalGroup(
            refreshLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
        );
        refreshLayout.setVerticalGroup(
            refreshLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(previous, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(img11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(me10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(img10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(me9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(img9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(me8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(img8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(me7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(img6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(me6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(img5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(me5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(img4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(me4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(img3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(me3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(img2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(me2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(img1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(me1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(54, 54, 54)
                        .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(me1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(img1)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(me2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(img2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(me3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(img3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(me4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(img4))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(me5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(img5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(me6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(img6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(me7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(img8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(me8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(img9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(me9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(img10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(me10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(img11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(previous, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel23))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 153, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Compose");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(0, 153, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Inbox");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cloudemail.png"))); // NOI18N

        jPanel11.setBackground(new java.awt.Color(0, 153, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Trash");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );

        username.setFont(new java.awt.Font("Showcard Gothic", 1, 48)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel12.setBackground(new java.awt.Color(0, 153, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Deactivate");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
        );

        previous1.setBackground(new java.awt.Color(0, 153, 255));
        previous1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                previous1MouseEntered(evt);
            }
        });

        jLabel53.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("Search");
        jLabel53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel53MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel53MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel53MouseExited(evt);
            }
        });

        javax.swing.GroupLayout previous1Layout = new javax.swing.GroupLayout(previous1);
        previous1.setLayout(previous1Layout);
        previous1Layout.setHorizontalGroup(
            previous1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(previous1Layout.createSequentialGroup()
                .addComponent(jLabel53, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addContainerGap())
        );
        previous1Layout.setVerticalGroup(
            previous1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel53, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        jPanel15.setBackground(new java.awt.Color(0, 153, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Sign out");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(previous1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(previous1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        error.setForeground(new java.awt.Color(255, 0, 51));

        confirmerror.setForeground(new java.awt.Color(255, 0, 0));
        confirmerror.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(error, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(confirmerror, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(546, 546, 546)
                .addComponent(confirmerror)
                .addGap(70, 70, 70)
                .addComponent(error)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1106, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jPanel6.setBackground(Color.MAGENTA);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jPanel6.setBackground(new java.awt.Color(0,153,255));
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
                jPanel7.setBackground(Color.MAGENTA);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
                jPanel7.setBackground(new java.awt.Color(0,153,255));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        // TODO add your handling code here:
                        jPanel11.setBackground(Color.MAGENTA);
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        // TODO add your handling code here:
                        jPanel11.setBackground(new java.awt.Color(0,153,255));
    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseEntered
        // TODO add your handling code here:
                                next.setBackground(Color.MAGENTA);
    }//GEN-LAST:event_jLabel21MouseEntered

    private void jLabel21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseExited
        // TODO add your handling code here:
                                next.setBackground(new java.awt.Color(0,153,255));
    }//GEN-LAST:event_jLabel21MouseExited

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:

        readmessages();
        if(multiprevious>=1)
        multiprevious--;
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        if(index%10==0)
        {index=index-20;}
        else{
        index=index-10-index%10;
        }
        readmessages();
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseEntered
        // TODO add your handling code here:
                                previous.setBackground(Color.MAGENTA);
    }//GEN-LAST:event_jLabel22MouseEntered

    private void jLabel22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseExited
        // TODO add your handling code here:
                                previous.setBackground(new java.awt.Color(0,153,255));
    }//GEN-LAST:event_jLabel22MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
Composedemo x=new Composedemo();
x.setVisible(true);
x.setuser(user);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void previousMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousMouseEntered
        // TODO add your handling code here:
                        previous.setBackground(Color.MAGENTA);
    }//GEN-LAST:event_previousMouseEntered

    private void previousMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousMouseExited
        // TODO add your handling code here:
                                previous.setBackground(new java.awt.Color(0,153,255));

    }//GEN-LAST:event_previousMouseExited

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked

        try {
            mails.deactivate(user);

            JOptionPane.showMessageDialog(null, "You are deactive now");
            try {
                Thread.sleep(40);
            } catch (InterruptedException ex) {
                Logger.getLogger(Composedemo.class.getName()).log(Level.SEVERE, null, ex);
            }
            signupdemo g=new signupdemo();
            g.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(Composedemo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        // TODO add your handling code here:
        jPanel12.setBackground(Color.MAGENTA);
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        // TODO add your handling code here:
        jPanel12.setBackground(new java.awt.Color(0,153,255));
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
      setuser(user);
      index=0;
setmessages();

    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel24MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseEntered
        // TODO add your handling code here:
                refresh.setBackground(Color.MAGENTA);
    }//GEN-LAST:event_jLabel24MouseEntered

    private void jLabel24MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseExited
        // TODO add your handling code here:
                refresh.setBackground(new java.awt.Color(0,153,255));

    }//GEN-LAST:event_jLabel24MouseExited

    private void refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseClicked
setmessages();
// TODO add your handling code here:
    }//GEN-LAST:event_refreshMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        inboxdemo x = new inboxdemo();
    IFolder n=new IFolder();
        n.name=user;
        n.Path="C:\\server/users/" +user + "/inbox/";
        try {
            mails.setViewingOptions(n, null, null);
        } catch (IOException ex) {
            Logger.getLogger(inboxdemo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(inboxdemo.class.getName()).log(Level.SEVERE, null, ex);
        }
        x.messages=mails.getmails();
        Single d=new Single();
        int i=0;
        while(i<x.messages.size())
        {d.add(true);
        i++;
        }
        x.read=d;
        x.readmessages();
                x.setVisible(true);
    x.setuser(user);
    this.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        trash x= new trash();
x.setuser(user);
x.setmessages();
x.setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_jLabel12MouseClicked
                    
    private void jLabel53MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel53MouseClicked
        // TODO add your handling code here:
        Splash11 x=new Splash11();
        x.from="sent";
        x.setuser(user);
                x.off();
        x.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel53MouseClicked

    private void jLabel53MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel53MouseEntered
        // TODO add your handling code here:
        previous1.setBackground(Color.MAGENTA);
    }//GEN-LAST:event_jLabel53MouseEntered

    private void jLabel53MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel53MouseExited
        // TODO add your handling code here:
        previous1.setBackground(new java.awt.Color(0,153,255));
    }//GEN-LAST:event_jLabel53MouseExited

    private void previous1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previous1MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_previous1MouseEntered

    private void metext1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_metext1MouseClicked
        // TODO add your handling code here:
          // TODO add your handling code here:
        if (!" ".equals(metext1.getText()))
        {
        IMail v= new IMail();
        String x=metext1.getText();
            try {
                v=mails.getmail(x);
            } catch (IOException | ParseException ex) {
                Logger.getLogger(inboxdemo.class.getName()).log(Level.SEVERE, null, ex);
            }
        Readmessage y= new Readmessage();
        y.setuser(user);
        y.setmail(v);
        y.setVisible(true);
        this.setVisible(false);}
    }//GEN-LAST:event_metext1MouseClicked

    private void metext2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_metext2MouseClicked
        // TODO add your handling code here:
         if (!" ".equals(metext2.getText()))
        {
        IMail v= new IMail();
        String x=metext2.getText();
            try {
                v=mails.getmail(x);
            } catch (IOException | ParseException ex) {
                Logger.getLogger(inboxdemo.class.getName()).log(Level.SEVERE, null, ex);
            }
        Readmessage y= new Readmessage();
        y.setuser(user);
        y.setmail(v);
        y.setVisible(true);
        this.setVisible(false);}
    }//GEN-LAST:event_metext2MouseClicked

    private void metext3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_metext3MouseClicked
        // TODO add your handling code here:
         if (!" ".equals(metext3.getText()))
        {
        IMail v= new IMail();
        String x=metext3.getText();
            try {
                v=mails.getmail(x);
            } catch (IOException | ParseException ex) {
                Logger.getLogger(inboxdemo.class.getName()).log(Level.SEVERE, null, ex);
            }
        Readmessage y= new Readmessage();
        y.setuser(user);
        y.setmail(v);
        y.setVisible(true);
        this.setVisible(false);}
    }//GEN-LAST:event_metext3MouseClicked

    private void metext4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_metext4MouseClicked
        // TODO add your handling code here:
         if (!" ".equals(metext4.getText()))
        {
        IMail v= new IMail();
        String x=metext4.getText();
            try {
                v=mails.getmail(x);
            } catch (IOException | ParseException ex) {
                Logger.getLogger(inboxdemo.class.getName()).log(Level.SEVERE, null, ex);
            }
        Readmessage y= new Readmessage();
        y.setuser(user);
        y.setmail(v);
        y.setVisible(true);
        this.setVisible(false);}
    }//GEN-LAST:event_metext4MouseClicked

    private void metext5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_metext5MouseClicked
        // TODO add your handling code here:
         if (!" ".equals(metext5.getText()))
        {
        IMail v= new IMail();
        String x=metext5.getText();
            try {
                v=mails.getmail(x);
            } catch (IOException | ParseException ex) {
                Logger.getLogger(inboxdemo.class.getName()).log(Level.SEVERE, null, ex);
            }
        Readmessage y= new Readmessage();
        y.setuser(user);
        y.setmail(v);
        y.setVisible(true);
        this.setVisible(false);}
    }//GEN-LAST:event_metext5MouseClicked

    private void metext6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_metext6MouseClicked
        // TODO add your handling code here:
         if (!" ".equals(metext6.getText()))
        {
        IMail v= new IMail();
        String x=metext6.getText();
            try {
                v=mails.getmail(x);
            } catch (IOException | ParseException ex) {
                Logger.getLogger(inboxdemo.class.getName()).log(Level.SEVERE, null, ex);
            }
        Readmessage y= new Readmessage();
        y.setuser(user);
        y.setmail(v);
        y.setVisible(true);
        this.setVisible(false);}
    }//GEN-LAST:event_metext6MouseClicked

    private void metext7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_metext7MouseClicked
        // TODO add your handling code here:
         if (!" ".equals(metext7.getText()))
        {
        IMail v= new IMail();
        String x=metext7.getText();
            try {
                v=mails.getmail(x);
            } catch (IOException | ParseException ex) {
                Logger.getLogger(inboxdemo.class.getName()).log(Level.SEVERE, null, ex);
            }
        Readmessage y= new Readmessage();
        y.setuser(user);
        y.setmail(v);
        y.setVisible(true);
        this.setVisible(false);}
    }//GEN-LAST:event_metext7MouseClicked

    private void metext8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_metext8MouseClicked
        // TODO add your handling code here:
         if (!" ".equals(metext8.getText()))
        {
        IMail v= new IMail();
        String x=metext8.getText();
            try {
                v=mails.getmail(x);
            } catch (IOException | ParseException ex) {
                Logger.getLogger(inboxdemo.class.getName()).log(Level.SEVERE, null, ex);
            }
        Readmessage y= new Readmessage();
        y.setuser(user);
        y.setmail(v);
        y.setVisible(true);
        this.setVisible(false);}
    }//GEN-LAST:event_metext8MouseClicked

    private void metext9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_metext9MouseClicked
        // TODO add your handling code here:
         if (!" ".equals(metext9.getText()))
        {
        IMail v= new IMail();
        String x=metext9.getText();
            try {
                v=mails.getmail(x);
            } catch (IOException | ParseException ex) {
                Logger.getLogger(inboxdemo.class.getName()).log(Level.SEVERE, null, ex);
            }
        Readmessage y= new Readmessage();
        y.setuser(user);
        y.setmail(v);
        y.setVisible(true);
        this.setVisible(false);}
    }//GEN-LAST:event_metext9MouseClicked

    private void metext10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_metext10MouseClicked
        // TODO add your handling code here:
         if (!" ".equals(metext10.getText()))
        {
        IMail v= new IMail();
        String x=metext10.getText();
            try {
                v=mails.getmail(x);
            } catch (IOException | ParseException ex) {
                Logger.getLogger(inboxdemo.class.getName()).log(Level.SEVERE, null, ex);
            }
        Readmessage y= new Readmessage();
        y.setuser(user);
        y.setmail(v);
        y.setVisible(true);
        this.setVisible(false);}
    }//GEN-LAST:event_metext10MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:    // TODO add your handling code here:
        signupdemo x= new signupdemo();
        x.setVisible(true);
        this.setVisible(false);
        }

        // TODO add your handling code here:
        {
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        // TODO add your handling code here:
        jPanel15.setBackground(Color.MAGENTA);
    }//GEN-LAST:event_jLabel16MouseEntered

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
        // TODO add your handling code here:
        jPanel15.setBackground(new java.awt.Color(0,153,255));
    }//GEN-LAST:event_jLabel16MouseExited
public void setmessages(){
 IFolder n=new IFolder();
 user=username.getText();
        n.name=user;
        n.Path="C:\\server/users/" +user + "/sent/";
        try {
            mails.setViewingOptions(n, null, null);
        } catch (IOException ex) {
            Logger.getLogger(inboxdemo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(inboxdemo.class.getName()).log(Level.SEVERE, null, ex);
        }
        messages=mails.getmails();
        Single d=new Single();
        int i=0;
        while(i<messages.size())
        {d.add(true);
        i++;
        }
        read=d;
        readmessages();

}
    
    public  void readmessages()
{
    
    if(index<10)
{
previous.setVisible(false);
}
else{
    previous.setVisible(true);
}
    if(messages.size()>index)
    {img1.setVisible(true);
        if(!(boolean)read.get(index))
        {
            img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/email-icoon~1.png"))); // NOI18N
        }
        else{
img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blue-mail-open-icon~1.png")));        
        }
    metext1.setText((String) messages.get(index));
    index++;
    }
    else{
        metext1.setText(" ");
    }
    if(messages.size()>index)
    {  img2.setVisible(true);

        if(!(boolean)read.get(index))
        {
            img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/email-icoon~1.png"))); // NOI18N
}
        else{
img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blue-mail-open-icon~1.png")));        

        }
    metext2.setText((String) messages.get(index));
    index++;
    }
    else{    
                img2.setVisible(false);
        metext2.setText(" ");
    }
    if(messages.size()>index)
    {                            img3.setVisible(true);
        if(!(boolean)read.get(index))
        {img3.setIcon(new javax.swing.ImageIcon("/email-icoon~1.png")); // NOI18N
}
        else{
        img3.setIcon(new javax.swing.ImageIcon("/blue-mail-open-icon~1.png")); // NOI18N

        }
    metext3.setText((String) messages.get(index));
    index++;
    }
    else{   
                        img3.setVisible(false);
        metext3.setText(" ");
    }
    if(messages.size()>index)
    {img4.setVisible(true);
        if(!(boolean)read.get(index))
        {img4.setIcon(new javax.swing.ImageIcon("/email-icoon~1.png")); // NOI18N
}
        else{
        img4.setIcon(new javax.swing.ImageIcon("/blue-mail-open-icon~1.png")); // NOI18N

        }
    metext4.setText((String) messages.get(index));
    index++;
    }
    else{    
                                img4.setVisible(false);
        metext4.setText(" ");
    }
    if(messages.size()>index)
    {img5.setVisible(true);

        if(!(boolean)read.get(index))
        {img5.setIcon(new javax.swing.ImageIcon("/email-icoon~1.png")); // NOI18N
}
        else{
        img5.setIcon(new javax.swing.ImageIcon("/blue-mail-open-icon~1.png")); // NOI18N

        }
    metext5.setText((String) messages.get(index));
    index++;
    }
    else{
                                        img5.setVisible(false);
        metext5.setText(" ");
    }
    if(messages.size()>index)
    {img6.setVisible(true);

        if(!(boolean)read.get(index))
        {img6.setIcon(new javax.swing.ImageIcon("/email-icoon~1.png")); // NOI18N
}
        else{
        img6.setIcon(new javax.swing.ImageIcon("/blue-mail-open-icon~1.png")); // NOI18N

        }
    metext6.setText((String) messages.get(index));
    index++;
    }
    else{
                                                img6.setVisible(false);
        metext6.setText(" ");
    }
    if(messages.size()>index)
    {img8.setVisible(true);
        if(!(boolean)read.get(index))
        {img8.setIcon(new javax.swing.ImageIcon("/email-icoon~1.png")); // NOI18N
}
        else{
        img8.setIcon(new javax.swing.ImageIcon("/blue-mail-open-icon~1.png")); // NOI18N

        }
    metext7.setText((String) messages.get(index));
    index++;
    }
    else{
                                                        img8.setVisible(false);
        metext7.setText(" ");
    }
    if(messages.size()>index)
    {img9.setVisible(true);
        if(!(boolean)read.get(index))
        {img9.setIcon(new javax.swing.ImageIcon("/email-icoon~1.png")); // NOI18N
}
        else{
        img9.setIcon(new javax.swing.ImageIcon("/blue-mail-open-icon~1.png")); // NOI18N

        }
    metext8.setText((String) messages.get(index));
    index++;
    }
    else{
                                                                img9.setVisible(false);
        metext8.setText(" ");
    }
    if(messages.size()>index)
    {img10.setVisible(true);
        if(!(boolean)read.get(index))
        {img10.setIcon(new javax.swing.ImageIcon("/email-icoon~1.png")); // NOI18N
}
        else{
        img10.setIcon(new javax.swing.ImageIcon("/blue-mail-open-icon~1.png")); // NOI18N

        }
    metext9.setText((String) messages.get(index));
    index++;
    }
    else{                                                                img10.setVisible(false);
        metext9.setText(" ");
    }
    if(messages.size()>index)
    {img11.setVisible(true);
        if(!(boolean)read.get(index))
        {img11.setIcon(new javax.swing.ImageIcon("/email-icoon~1.png")); // NOI18N
}
        else{
        img11.setIcon(new javax.swing.ImageIcon("/blue-mail-open-icon~1.png")); // NOI18N

        }
    metext10.setText((String) messages.get(index));
    index++;
    }
    else{
        img11.setVisible(false);
        metext10.setText(" ");
    }
   if(index==messages.size())
   {
   next.setVisible(false);
   
   }
   else{   next.setVisible(true);
}
   max=index;
   if(index<=10)
   {min=0;}
else
   {if(index%10==0)
       min=index-10;
           else
           min=index-index%10;
   }
      jLabel23.setText("from "+ min +" to "+max);
}
public void setuser(String s){

user=s;
username.setText(user);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signupdemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signupdemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signupdemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signupdemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new sent().setVisible(true);              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel confirmerror;
    private javax.swing.JLabel error;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img10;
    private javax.swing.JLabel img11;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel img4;
    private javax.swing.JLabel img5;
    private javax.swing.JLabel img6;
    private javax.swing.JLabel img8;
    private javax.swing.JLabel img9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPanel me1;
    private javax.swing.JPanel me10;
    private javax.swing.JPanel me2;
    private javax.swing.JPanel me3;
    private javax.swing.JPanel me4;
    private javax.swing.JPanel me5;
    private javax.swing.JPanel me6;
    private javax.swing.JPanel me7;
    private javax.swing.JPanel me8;
    private javax.swing.JPanel me9;
    private javax.swing.JLabel metext1;
    private javax.swing.JLabel metext10;
    private javax.swing.JLabel metext2;
    private javax.swing.JLabel metext3;
    private javax.swing.JLabel metext4;
    private javax.swing.JLabel metext5;
    private javax.swing.JLabel metext6;
    private javax.swing.JLabel metext7;
    private javax.swing.JLabel metext8;
    private javax.swing.JLabel metext9;
    private javax.swing.JPanel next;
    private javax.swing.JPanel previous;
    private javax.swing.JPanel previous1;
    private javax.swing.JPanel refresh;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
